### ISSUE TITLE
关于pyhon处理时间的相关内容

### ISSUE THREAD

**Issue by mryanli** [woaielf/woaielf.github.io#3]
迷妹你好，看了你的博客，感觉很好，pyhton的思维导图里可以把关于时间函数的内容放进去，我觉则一门语言处理，基础数据类型部分包含字符，数字，时间就比较完美了

**Comment by mryanli** [comment]
python笔记八里，进程&线程的思维导图放了重复两张。

**Comment by woaielf** [comment]
收到~~下一版本会进行改进哒
